#!/command/with-contenv bash
# shellcheck shell=bash
# Start the Arkos service

set -o errexit -o nounset -o pipefail

# opt out of openvino telemetry
if [ -e /usr/local/bin/opt_in_out ]; then
  /usr/local/bin/opt_in_out --opt_out
fi

# Logs should be sent to stdout so that s6 can collect them

# Tell S6-Overlay not to restart this service
s6-svc -O .

function set_libva_version() {
    local ffmpeg_path
    ffmpeg_path=$(python3 /usr/local/ffmpeg/get_ffmpeg_path.py)
    LIBAVFORMAT_VERSION_MAJOR=$("$ffmpeg_path" -version | grep -Po "libavformat\W+\K\d+")
    export LIBAVFORMAT_VERSION_MAJOR
}

echo "[INFO] Preparing Arkos..."
set_libva_version

echo "[INFO] Starting Arkos..."

cd /opt/arkos || echo "[ERROR] Failed to change working directory to /opt/arkos"

# Replace the bash process with the Arkos process, redirecting stderr to stdout
exec 2>&1
exec python3 -u -m arkos
